#!/usr/bin/env python3
"""Generate T047: 50 VAR and assisted officiating rules (append).

Network: none (local structured data). Outbound HTTP must use fetch_utils.RateLimitedFetcher (>=1s/request); see docs/maintainers/data-collection-policy.md and .cursor/rules/world-cup-data-collection.mdc."""

from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "data" / "knowledge_rules.csv"
START_ID = 351

COLUMNS = [
    "id", "category_l1", "category_l2", "category_l3", "scope", "priority",
    "question", "question_aliases", "answer_short", "answer_detail", "answer_format",
    "keywords", "tags", "entities", "related_ids", "difficulty",
    "era_start", "era_end", "region", "language", "fact_type", "confidence",
    "source_type", "source_ref", "content_flags", "updated_at",
]

ENTRIES = [
    ("VAR定义", "VAR是什么?", "视频助理裁判",
     "视频助理裁判团队通过回放协助主裁纠正清晰严重误判。",
     "2018世界杯起全面用于正赛。",
     "VAR,视频,助理,误判", "入门", ""),
    ("VAR全称", "VAR英文全称?", "Video Assistant Referee",
     "Video Assistant Referee，视频助理裁判。",
     "与球场主裁、助理裁判分工协作。",
     "VAR,英文,全称,裁判", "入门", ""),
    ("最小干预", "VAR干预原则?", "最小干预原则",
     "仅纠正清晰且严重的错误，避免过度干预比赛流畅性。",
     "主观轻微分歧通常维持原判。",
     "VAR,最小干预,清晰,严重", "入门", ""),
    ("回看类型", "VAR可回看哪些?", "VAR回看范围",
     "进球、点球、直红、错人身份四类清晰严重错误。",
     "其他犯规通常不在VAR纠正范围。",
     "VAR,回看,进球,点球", "入门", ""),
    ("进球复核", "VAR如何复核进球?", "进球越位",
     "检查进球前越位、手球、犯规等，确认有效或取消。",
     "越位以体线部位为准。",
     "VAR,进球,越位,取消", "入门", ""),
    ("点球复核", "VAR会建议点球吗?", "点球回看",
     "禁区内遗漏的严重犯规或手球，VAR可建议主裁回看后改判点球。",
     "主裁须亲自查看屏幕。",
     "VAR,点球,回看,改判", "进阶", ""),
    ("直红复核", "VAR会补发红牌吗?", "直红回看",
     "遗漏的严重暴力或破坏明显进球机会，可建议直红。",
     "两黄变红不在VAR纠正范围。",
     "VAR,直红,回看,补发", "进阶", ""),
    ("错人复核", "VAR错人纠正?", "错牌错人",
     "若处罚对象错误且影响比赛，VAR可建议纠正。",
     "罕见但规则允许。",
     "VAR,错人,纠正,处罚", "进阶", ""),
    ("主裁屏幕", "主裁在哪看回放?", "场边屏幕",
     "主裁至场边指定屏幕观看回放，称现场回看。",
     "观众亦可见转播回放画面。",
     "主裁,屏幕,回看,现场", "入门", ""),
    ("静默复核", "VAR静默检查?", "静默检查",
     "多数时间VAR后台检查，无问题不通知主裁。",
     "减少不必要中断。",
     "VAR,静默,检查,通知", "入门", ""),
    ("VAR信号", "VAR如何通知主裁?", "VAR沟通",
     "VAR通过耳机建议「回看」或「维持」；主裁可接受或拒绝。",
     "最终决定权在主裁。",
     "VAR,耳机,建议,主裁", "入门", ""),
    ("越位线", "VAR越位怎么画线?", "半自动越位",
     "半自动越位技术用多机位生成体线，辅助VAR判断。",
     "2022世界杯起广泛应用。",
     "VAR,越位,体线,半自动", "进阶", "time_sensitive"),
    ("体线部位", "越位看哪个部位?", "越位体线",
     "进攻方可得分部位（头、躯干、脚）相对防守方最靠前部位。",
     "手臂不算越位部位。",
     "越位,体线,手臂,部位", "进阶", ""),
    ("毫米越位", "体线越位算吗?", "体线越位",
     "体线任何部分超前即越位，无论差距多小。",
     "半自动系统提高精度。",
     "体线,越位,毫米,精度", "进阶", ""),
    ("进球庆祝后", "庆祝后VAR取消进球?", "庆祝后改判",
     "可在庆祝后回看并取消进球，进球无效。",
     "教练与球员须适应延迟确认。",
     "VAR,庆祝,取消,进球", "入门", ""),
    ("手球进球", "手球后进球VAR?", "手球进球",
     "进攻方手球参与进攻或进球，VAR可建议取消。",
     "手臂位置是否自然为关键。",
     "VAR,手球,进球,取消", "进阶", ""),
    ("犯规进球", "犯规后进球VAR?", "犯规在先",
     "进球前对门将或防守队员犯规，VAR可建议取消进球。",
     "包括推搡、拉拽等。",
     "VAR,犯规,进球,取消", "进阶", ""),
    ("未判点球", "漏判点球VAR?", "漏判十二码",
     "禁区内清晰严重犯规未判，VAR建议回看并可能改判点球。",
     "轻微接触可能不介入。",
     "VAR,漏判,点球,回看", "进阶", ""),
    ("误判点球", "VAR会取消点球吗?", "取消点球",
     "若回放显示无犯规或犯规发生在禁区外，可改判任意球或继续。",
     "主裁观看后决定。",
     "VAR,取消,点球,误判", "进阶", ""),
    ("门将越位", "点球VAR看门将?", "门将点球越位",
     "点球大战与常规点球可复核门将提前移动。",
     "明显越线可令重踢。",
     "VAR,门将,点球,越线", "进阶", ""),
    ("世界杯VAR", "世界杯何时用VAR?", "2018VAR",
     "2018俄罗斯世界杯起淘汰赛与小组赛全面使用VAR。",
     "2018前无VAR。",
     "世界杯,VAR,2018,全面", "入门", "time_sensitive"),
    ("2022技术", "2022世界杯VAR技术?", "半自动越位2022",
     "2022卡塔尔世界杯使用半自动越位与更清晰的回放流程。",
     "仍由主裁最终决定。",
     "2022,VAR,半自动,世界杯", "入门", "time_sensitive"),
    ("女足VAR", "女足世界杯有VAR吗?", "女足VAR",
     "女子世界杯正赛同样配备VAR，规则框架与男子一致。",
     "依当届赛事装备。",
     "女足,VAR,世界杯,一致", "入门", ""),
    ("联赛VAR", "联赛VAR一样吗?", "联赛VAR",
     "各国联赛依足协与IFAB协议部署，核心四类回看相同。",
     "装备水平可能不同。",
     "联赛,VAR,协议,回看", "入门", ""),
    ("无VAR比赛", "没有VAR怎么办?", "无VAR",
     "无VAR时完全依场上裁判判罚，赛后不 retro 改分。",
     "业余赛通常无VAR。",
     "无VAR,判罚,场上,业余", "入门", ""),
    ("延迟开球", "VAR时比赛暂停?", "比赛中断",
     "回看期间比赛暂停，时钟继续由裁判管理补时。",
     "补时通常增加以补偿VAR时间。",
     "VAR,暂停,补时,中断", "入门", ""),
    ("球迷屏幕", "球迷能否看回放?", "转播回放",
     "转播可播放回放，球场大屏依规程可能不播争议片段。",
     "避免煽动冲突。",
     "球迷,回放,大屏,转播", "入门", ""),
    ("争议文化", "VAR为何有争议?", "VAR争议",
     "干预时机、划线精度、主观犯规标准引发讨论。",
     "规则仍强调主裁最终决定。",
     "VAR,争议,标准,讨论", "入门", ""),
    ("流畅性", "VAR影响比赛节奏?", "节奏中断",
     "回看增加停顿，IFAB通过最小干预与静默检查缓解。",
     "重大错误纠正被视为收益。",
     "VAR,节奏,停顿,干预", "入门", ""),
    ("教练抗议", "教练抗议VAR?", "抗议VAR",
     "对VAR结果激烈抗议仍可黄牌，不得进入回看区。",
     "质疑判罚不改变世界结果。",
     "教练,抗议,VAR,黄牌", "入门", ""),
    ("球员围屏", "球员能围观看屏吗?", "围屏处罚",
     "球员围拢场边屏幕可黄牌，仅主裁查看。",
     "维持秩序。",
     "球员,围屏,黄牌,秩序", "入门", ""),
    ("AVAR角色", "AVAR是什么?", "助理VAR",
     "Assistant VAR协助主VAR沟通与检查，分工协作。",
     "团队多人值守监控室。",
     "AVAR,助理,团队,监控", "进阶", ""),
    ("回放操作员", "回放操作员做什么?", "RO角色",
     "Replay Operator提供角度与慢镜，不做出判罚决定。",
     "供VAR与主裁参考。",
     "回放,操作员,角度,慢镜", "进阶", ""),
    ("IFAB协议", "VAR规则依据?", "VAR协议",
     "IFAB《足球竞赛规则》附录及VAR协议规定实施细节。",
     "与Law 5裁判章节配合。",
     "IFAB,VAR,协议,附录", "专业", ""),
    ("仅四类", "VAR能改任意犯规吗?", "四类限制",
     "非进球、点球、直红、错人四类，通常不由VAR改判。",
     "黄牌遗漏一般不回看。",
     "VAR,四类,限制,改判", "入门", ""),
    ("主观犯规", "VAR对轻微犯规?", "主观接触",
     "轻微接触或合理拼抢，VAR多维持原判。",
     "清晰严重是门槛。",
     "VAR,主观,轻微,维持", "进阶", ""),
    ("越位配合", "越位配合进攻?", "越位配合",
     "传球瞬间进攻方球员体线超前即越位，VAR精确判定。",
     "配合战术不改变越位规则。",
     "VAR,越位,传球,体线", "进阶", ""),
    ("界外球误判", "界外球VAR管吗?", "界外球VAR",
     "通常不在VAR四类内，明显错判若影响进球链可能间接涉及。",
     "多数界外球争议不回看。",
     "界外球,VAR,范围,错判", "进阶", ""),
    ("经典改判", "世界杯VAR经典改判?", "VAR案例",
     "2018点球改判、2022半自动越位等为例，规则框架不变。",
     "案例用于理解非修改规则。",
     "世界杯,VAR,案例,改判", "入门", ""),
    ("训练裁判", "VAR裁判如何培训?", "VAR培训",
     "国际足联与协会对VAR团队统一培训与认证。",
     "与场上裁判同等重要。",
     "VAR,培训,认证,裁判", "专业", ""),
    ("费用设备", "VAR设备成本?", "VAR成本",
     "多机位、专线、监控室成本高，由赛事主办方承担。",
     "非规则内容但解释普及度。",
     "VAR,设备,成本,主办", "入门", ""),
    ("未来修订", "VAR规则还会改吗?", "VAR修订",
     "IFAB持续评估干预标准与越位技术，世界杯依当届指引。",
     "最小干预原则预计保留。",
     "VAR,修订,IFAB,未来", "专业", "time_sensitive"),
    ("业余误解", "VAR能改比分吗?", "改分误解",
     "VAR仅影响场上后续判罚与进球有效，赛后不 retro 改赛果。",
     "终场哨后争议提交报告。",
     "误解,VAR,比分,赛后", "入门", ""),
    ("业余误解2", "球员要求VAR?", "球员要求回看",
     "球员不得要求VAR介入，做手势可能黄牌。",
     "仅裁判团队启动回看。",
     "误解,球员,要求,黄牌", "入门", ""),
    ("点球大战VAR", "点球大战用VAR吗?", "大战VAR",
     "点球大战中门将越线、主罚违例等可适用VAR复核。",
     "与常规点球规则衔接。",
     "点球大战,VAR,门将,复核", "进阶", ""),
    ("加时VAR", "加时赛VAR一样吗?", "加时VAR",
     "加时赛VAR规则与正赛相同，四类回看适用。",
     "补时亦计入损失时间。",
     "加时,VAR,规则,补时", "入门", ""),
    ("进球后快速", "快速开球VAR?", "快速开球",
     "对方快速开球后VAR仍可回看此前犯规并取消进球。",
     "裁判管理开球时机。",
     "VAR,快速开球,取消,犯规", "进阶", ""),
    ("透明度", "VAR沟通透明吗?", "透明沟通",
     "部分赛事试验向观众播报最终决定原因。",
     "非全球强制。",
     "VAR,透明,播报,决定", "入门", "time_sensitive"),
    ("与门线", "VAR与门线技术?", "GLT与VAR",
     "门线技术判定球是否进门，VAR处理进球前犯规与越位。",
     "二者互补。",
     "门线,VAR,进球,互补", "进阶", ""),
    ("纪律VAR", "VAR后纪律追加?", "赛后纪律",
     "VAR确认暴力等行为后，场上处罚有效并可能赛后追加。",
     "不改变已出示牌效力。",
     "VAR,纪律,暴力,追加", "进阶", ""),
]


def row(seq: int, entry: tuple) -> dict[str, str]:
    *base, flags = entry if len(entry) == 8 else (*entry, "")
    l3, q, aliases, short, detail, kw, diff = base[:7]
    return {
        "id": f"WC-RULE-{seq:05d}",
        "category_l1": "规则与裁判",
        "category_l2": "VAR与辅助判罚",
        "category_l3": l3,
        "scope": "football_general",
        "priority": "5",
        "question": q,
        "question_aliases": aliases,
        "answer_short": short,
        "answer_detail": detail,
        "answer_format": "definition",
        "keywords": kw,
        "tags": "VAR,视频",
        "entities": "",
        "related_ids": "WC-GLOS-00047",
        "difficulty": diff,
        "era_start": "",
        "era_end": "",
        "region": "全球",
        "language": "zh-CN",
        "fact_type": "rule",
        "confidence": "official",
        "source_type": "IFAB",
        "source_ref": "IFAB Laws of the Game 2024/25 VAR Protocol",
        "content_flags": flags,
        "updated_at": "2026-06-03",
    }


def main() -> None:
    assert len(ENTRIES) == 50
    new_rows = [row(START_ID + i - 1, e) for i, e in enumerate(ENTRIES, start=1)]
    existing: list[dict[str, str]] = []
    if OUTPUT.exists():
        with OUTPUT.open(newline="", encoding="utf-8") as f:
            existing = [dict(r) for r in csv.DictReader(f) if (r.get("id") or "").strip()]

    ids = {r["id"] for r in existing}
    for r in new_rows:
        if r["id"] in ids:
            raise SystemExit(f"duplicate id {r['id']}")

    with OUTPUT.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=COLUMNS, lineterminator="\n")
        writer.writeheader()
        writer.writerows(existing)
        writer.writerows(new_rows)
    print(f"Appended {len(new_rows)} rows (total {len(existing) + len(new_rows)})")


if __name__ == "__main__":
    main()
