#!/usr/bin/env python3
"""Generate T052: 50 2026 rule and tournament changes (append).

Network: none (local structured data). Outbound HTTP must use fetch_utils.RateLimitedFetcher (>=1s/request); see docs/maintainers/data-collection-policy.md and .cursor/rules/world-cup-data-collection.mdc."""

from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "data" / "knowledge_rules.csv"
START_ID = 601

COLUMNS = [
    "id", "category_l1", "category_l2", "category_l3", "scope", "priority",
    "question", "question_aliases", "answer_short", "answer_detail", "answer_format",
    "keywords", "tags", "entities", "related_ids", "difficulty",
    "era_start", "era_end", "region", "language", "fact_type", "confidence",
    "source_type", "source_ref", "content_flags", "updated_at",
]

ENTRIES = [
    ("2026主办", "2026世界杯在哪办?", "美加墨",
     "由美国、加拿大、墨西哥联合举办，史上首次三国合办。",
     "具体场馆以当届组委会公布为准。",
     "2026,主办,美加墨,合办", "入门", "rule_change_2026"),
    ("48队扩军", "2026多少队参赛?", "48支球队",
     "决赛圈扩军至48支球队，较32队赛制增加16席。",
     "预选赛名额分配随之调整。",
     "2026,48队,扩军,决赛圈", "入门", "rule_change_2026"),
    ("赛制变化", "2026小组赛赛制?", "新赛制",
     "48队通常分12组每组4队，前两名加部分第三名晋级淘汰赛。",
     "精确晋级规则以FIFA当届规程为准。",
     "2026,小组赛,晋级,48队", "入门", "rule_change_2026"),
    ("比赛场次", "2026总场次增加?", "场次",
     "参赛队增多使小组赛与淘汰赛总场次高于32队时代。",
     "赛程跨度可能更长。",
     "2026,场次,增加,赛程", "入门", "rule_change_2026"),
    ("跨时区", "2026跨时区影响?", "时区",
     "三国幅员大，球队旅行与时差管理成为新课题。",
     "竞赛规程规定休息间隔下限。",
     "2026,时区,旅行,休息", "入门", "time_sensitive"),
    ("高温赛事", "2026夏季高温?", "气候",
     "部分场馆夏季气温高，补水暂停与比赛时间可能依规程调整。",
     "球员安全为优先。",
     "2026,高温,补水,安全", "入门", "time_sensitive"),
    ("换人名额", "2026换人几次?", "五人换人",
     "正赛通常允许每队最多五次换人，加时可能额外名额。",
     "以当届理事会批准的竞赛规程为准。",
     "2026,换人,五次,规程", "入门", "rule_change_2026"),
    ("脑震荡换人", "2026脑震荡换人?", "额外换人",
     "若启用脑震荡换人协议，可能不计入常规五人名额。",
     "依IFAB与FIFA当届联合指引。",
     "2026,脑震荡,换人,协议", "进阶", "rule_change_2026"),
    ("加时换人", "2026加时换人?", "加时名额",
     "加时赛可能允许额外一次换人机会。",
     "具体以2026世界杯规程条文为准。",
     "2026,加时,换人,额外", "进阶", "rule_change_2026"),
    ("VAR延续", "2026还用VAR吗?", "VAR",
     "预计继续使用VAR及半自动越位等辅助判罚技术。",
     "细则随IFAB年度更新。",
     "2026,VAR,半自动,越位", "入门", "rule_change_2026"),
    ("半自动越位", "2026越位技术?", "SAOT",
     "半自动越位辅助预计沿用，提高体线判罚一致性。",
     "主裁仍做最终决定。",
     "2026,半自动,越位,体线", "入门", "rule_change_2026"),
    ("门线技术", "2026门线技术?", "GLT",
     "门线技术预计在所有比赛球场配备。",
     "与VAR分工互补。",
     "2026,门线,技术,进球", "入门", "rule_change_2026"),
    ("裁判交流", "2026裁判播报?", "透明",
     "可能扩大向观众播报判罚决定试验。",
     "非强制但趋势增加。",
     "2026,裁判,播报,透明", "入门", "time_sensitive"),
    ("补水暂停", "2026补水规则?", "冷却",
     "高温场次可能设官方补水暂停，依竞赛规程。",
     "通常上下半场各一次窗口。",
     "2026,补水,暂停,高温", "入门", "rule_change_2026"),
    ("竞赛球", "2026官方用球?", "比赛用球",
     "阿迪达斯等赞助商发布当届官方比赛球。",
     "球规格须符合IFAB标准。",
     "2026,用球,官方,规格", "入门", "time_sensitive"),
    ("视频回放", "2026转播VAR?", "转播",
     "转播可展示VAR过程，球场大屏依规程可能限制。",
     "与2018以来实践类似。",
     "2026,转播,VAR,大屏", "入门", "time_sensitive"),
    ("预选赛扩军", "2026预选赛变化?", "名额",
     "各大洲配额因48席重新分配，更多队有机会晋级。",
     "洲际足联细则各异。",
     "2026,预选赛,配额,洲际", "入门", "rule_change_2026"),
    ("东道主名额", "2026东道主直通?", "直通",
     "美加墨作为东道主通常获决赛圈席位。",
     "联合主办名额分配依FIFA决定。",
     "2026,东道主,直通,席位", "入门", "rule_change_2026"),
    ("开球时间", "2026开球本地时间?", "开球",
     "为适应北美电视市场，部分开球可能午后或晚间。",
     "全球转播时差需观众留意。",
     "2026,开球,时间,转播", "入门", "time_sensitive"),
    ("决赛地点", "2026决赛在哪?", "决赛场馆",
     "决赛场馆由组委会选定并提前公布。",
     "可能为美国大型球场。",
     "2026,决赛,场馆,美国", "入门", "time_sensitive"),
    ("季军战", "2026还有季军战?", "三四名",
     "世界杯传统三四名决赛预计保留。",
     "赛程夹在半决赛与决赛之间。",
     "2026,季军战,三四名,赛程", "入门", "rule_change_2026"),
    ("点球大战", "2026点球规则变吗?", "点球",
     "淘汰赛平局后点球大战规则与IFAB一致，预计不变。",
     "大战程序依规程。",
     "2026,点球,大战,淘汰赛", "入门", "rule_change_2026"),
    ("金球制", "2026还有金球?", "突然死亡",
     "加时金球制已废除，2026仍采用30分钟加时。",
     "仍平则点球。",
     "2026,加时,金球,废除", "入门", "rule_change_2026"),
    ("补时惯例", "2026补时会更长?", "补时",
     "裁判继续根据损失时间补时，大赛可能偏长。",
     "非2026专属规则变更。",
     "2026,补时,损失,裁判", "入门", "time_sensitive"),
    ("种族歧视", "2026反歧视程序?", "SOS",
     "可能沿用三步反歧视停赛程序（依当届指引）。",
     "队长与裁判沟通机制。",
     "2026,歧视,停赛,程序", "进阶", "rule_change_2026"),
    ("队长臂章", "2026队长标识?", "袖标",
     "队长继续佩戴袖标，可能推广反歧视信息臂章。",
     "依FIFA社会责任倡议。",
     "2026,队长,袖标,倡议", "入门", "time_sensitive"),
    ("球衣号码", "2026号码规则?", "背号",
     "1–99号码规则不变，门将须区分颜色。",
     "名单截止前确定。",
     "2026,号码,球衣,名单", "入门", "rule_change_2026"),
    ("大名单人数", "2026大名单几人?", "26人",
     "近年世界杯大名单多为26人，2026预计相近。",
     "以当届注册规程为准。",
     "2026,大名单,26人,注册", "入门", "rule_change_2026"),
    ("替补门将", "2026门将名额?", "三门将",
     "大名单通常含三名门将，与其他位置共用名额。",
     "无单独增加第四门将规则。",
     "2026,门将,大名单,三人", "入门", "rule_change_2026"),
    ("女足对比", "2026与女足扩军?", "女足",
     "女子世界杯亦有扩军讨论，男子2026先至48队。",
     "规则框架仍依IFAB。",
     "2026,女足,扩军,对比", "入门", "time_sensitive"),
    ("俱乐部放行", "2026俱乐部放人?", "释放",
     "俱乐部须在 FIFA 协调窗口释放国脚参加世界杯。",
     "伤病与保险依国际转会条例。",
     "2026,俱乐部,国脚,释放", "专业", "rule_change_2026"),
    ("药物检测", "2026反兴奋剂?", "WADA",
     "继续WADA与FIFA反兴奋剂检测，赛内赛外均有。",
     "与规则变更无直接关系。",
     "2026,反兴奋剂,WADA,检测", "专业", "rule_change_2026"),
    ("视频助理培训", "2026VAR裁判组?", "裁判培训",
     "赛前集中培训VAR与半自动系统操作。",
     "裁判名单提前公布。",
     "2026,VAR,培训,裁判", "专业", "rule_change_2026"),
    ("草皮标准", "2026球场草皮?", "场地",
     "天然草为主，草皮标准依FIFA场地手册。",
     "人工草仅特殊情况。",
     "2026,草皮,场地,标准", "入门", "time_sensitive"),
    ("交通物流", "2026球队交通?", "物流",
     "跨国组别导致航班与大巴行程增加。",
     "组委会提供官方交通窗口。",
     "2026,交通,物流,行程", "入门", "time_sensitive"),
    ("球迷签证", "2026观赛签证?", "签证",
     "三国签证政策各异，国际观众须提前规划。",
     "非竞赛规则但影响观赛。",
     "2026,签证,观赛,三国", "入门", "time_sensitive"),
    ("安全规程", "2026赛场安全?", "安保",
     "赛场安检与禁品清单依当地法规与FIFA安保标准。",
     "与比赛规则并行。",
     "2026,安保,安检,赛场", "入门", "time_sensitive"),
    ("未成年球员", "2026年龄限制?", "年龄",
     "无硬性最低年龄，符合健康与注册即可。",
     "历史上有未成年参赛先例。",
     "2026,年龄,注册,参赛", "入门", "rule_change_2026"),
    ("联合训练", "2026赛前训练营?", "训练营",
     "各队赛前在北美设营，适应气候与时区。",
     "友谊赛安排依赛程。",
     "2026,训练营,适应,友谊赛", "入门", "time_sensitive"),
    ("IFAB同步", "2026适用哪版规则?", "规则版本",
     "赛场适用当届批准的IFAB规则版本及解释。",
     "2025/26文本可能生效。",
     "2026,IFAB,版本,解释", "专业", "rule_change_2026"),
    ("手球标准", "2026手球会变吗?", "手球",
     "手球依IFAB最新解释，2026无单独世界杯手球条文。",
     "强调手臂不自然扩大。",
     "2026,手球,IFAB,扩大", "入门", "rule_change_2026"),
    ("越位标准", "2026越位标准?", "越位",
     "体线越位与半自动辅助继续，无放宽传闻。",
     "毫米级判定仍有效。",
     "2026,越位,体线,半自动", "入门", "rule_change_2026"),
    ("科技试验", "2026新科技试验?", "试验",
     "FIFA可能试验新数据或裁判辅助，须理事会批准。",
     "未批准技术不得用于判罚。",
     "2026,科技,试验,批准", "专业", "time_sensitive"),
    ("赛制争议", "48队赛制争议?", "讨论",
     "扩军后小组赛质量与赛程长度引发讨论。",
     "规则已定则按规程执行。",
     "2026,48队,争议,质量", "入门", "time_sensitive"),
    ("积分规则", "2026小组赛积分?", "积分",
     "胜3平1负0，净胜球与进球数决定同分排名。",
     "与近年世界杯一致。",
     "2026,积分,净胜球,排名", "入门", "rule_change_2026"),
    ("红黄牌累计", "2026黄牌累计?", "停赛",
     "小组赛黄牌累计可能导致淘汰赛停赛，阈值依规程。",
     "半决赛后常清零。",
     "2026,黄牌,停赛,累计", "入门", "rule_change_2026"),
    ("业余关注", "业余球迷看2026须知?", "观赛",
     "赛制扩军意味着更多场次与球队，规则核心仍为IFAB。",
     "关注当届规程更新即可。",
     "2026,观赛,扩军,IFAB", "入门", "time_sensitive"),
    ("历史对比", "2026与1994美国赛?", "1994",
     "1994亦为美国主办32队赛制，2026规模更大。",
     "规则科技水平显著提升。",
     "2026,1994,美国,对比", "入门", "time_sensitive"),
    ("未来影响", "2026对下届影响?", "遗产",
     "48队经验将影响未来洲际赛与世界杯筹办。",
     "IFAB规则仍全球统一。",
     "2026,遗产,扩军,筹办", "专业", "rule_change_2026"),
    ("官方用球", "2026比赛用球规格?", "用球规格",
     "官方用球须符合IFAB圆度、重量与气压标准。",
     "赛前由裁判检查并选定。",
     "2026,用球,规格,检查", "入门", "rule_change_2026"),
]


def row(seq: int, entry: tuple) -> dict[str, str]:
    *base, flags = entry if len(entry) == 8 else (*entry, "")
    l3, q, aliases, short, detail, kw, diff = base[:7]
    if not flags:
        flags = "rule_change_2026"
    return {
        "id": f"WC-RULE-{seq:05d}",
        "category_l1": "规则与裁判",
        "category_l2": "2026规则变化",
        "category_l3": l3,
        "scope": "world_cup",
        "priority": "5",
        "question": q,
        "question_aliases": aliases,
        "answer_short": short,
        "answer_detail": detail,
        "answer_format": "definition",
        "keywords": kw,
        "tags": "2026,规则变化",
        "entities": "",
        "related_ids": "WC-GLOS-00453",
        "difficulty": diff,
        "era_start": "2026",
        "era_end": "",
        "region": "全球",
        "language": "zh-CN",
        "fact_type": "rule",
        "confidence": "official",
        "source_type": "FIFA",
        "source_ref": "FIFA World Cup 2026 Regulations (draft/edition per release)",
        "content_flags": flags,
        "updated_at": "2026-06-03",
    }


def main() -> None:
    assert len(ENTRIES) == 50
    new_rows = [row(START_ID + i - 1, e) for i, e in enumerate(ENTRIES, start=1)]
    existing: list[dict[str, str]] = []
    if OUTPUT.exists():
        with OUTPUT.open(newline="", encoding="utf-8") as f:
            existing = [dict(r) for r in csv.DictReader(f) if (r.get("id") or "").strip()]

    ids = {r["id"] for r in existing}
    for r in new_rows:
        if r["id"] in ids:
            raise SystemExit(f"duplicate id {r['id']}")

    with OUTPUT.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=COLUMNS, lineterminator="\n")
        writer.writeheader()
        writer.writerows(existing)
        writer.writerows(new_rows)
    print(f"Appended {len(new_rows)} rows (total {len(existing) + len(new_rows)})")


if __name__ == "__main__":
    main()
